server:
  port: 8081
spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/zonaGamer
    username: postgres
    password: 1234
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  kafka:
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.apache.kafka.common.serialization.StringSerializer
    consumer:
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      group-id: game-service-group
    bootstrap-servers: localhost:9092
    topics:
      user-events: user-events
  cloud: 
    function:
      definition: 
      stream:
        default-binder: kafka_default
        bindings:
          gameBinding-out-0: 
            destination: event.game-created
            binder: kafka_default
            useNativeDeCoding: true
        binders:
          kafka_default:
            type: kafka
            environment: 
              spring:
                cloud:
                 stream:
                  kafka:
                    default:
                      consumer: 
                        configuration: 
                          session.timeout.ms: 10000
                          max.poll.records: 10 
                      producer: 
                        compressionType: gzip
                        configuration: 
                          max.request.size: 1000000000
                    binder:
                      autoAddPartitions: true 
                      autoCreateTopics: true 
                      requiredAcks: -1
                      minPartitionCount: 3
                      replicationFactor: 1
                      serdeError: logAndContinue
                      brokers: localhost:9092

management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics
  endpoint:
    health:
      show-details: always
      probes:
        enabled: true
